export interface GridData {
    ticketId: string,
    client: string,
    subject: string,
    category: string,
    serverity: string,
    currentStatus: string,
    loggedOn: string,
    logggedBy: string,
    currentWith: string,
    noOfJobs: string,
    action?: string
}



export const gridData: GridData[] = [
    {
        ticketId: 'Ticket Id here',
        client: 'Client Here',
        subject: 'subject Here',
        category: 'category Here',
        serverity: 'serverity Here',
        currentStatus: 'Logged',
        loggedOn: 'Occured',
        logggedBy: 'Jenny Penz',
        currentWith: 'Client Here',
        noOfJobs: 'Client Here',
        action: '',
    },
    {
        ticketId: 'Ticket Id here',
        client: 'Client Here',
        subject: 'subject Here',
        category: 'category Here',
        serverity: 'serverity Here',
        currentStatus: 'Recieved',
        loggedOn: 'Occured',
        logggedBy: 'Jenny Penz',
        currentWith: 'Client Here',
        noOfJobs: 'Client Here',
        action: '',
    },
    {
        ticketId: 'Ticket Id here',
        client: 'Client Here',
        subject: 'subject Here',
        category: 'category Here',
        serverity: 'serverity Here',
        currentStatus: 'InProgress',
        loggedOn: 'Occured',
        logggedBy: 'Jenny Penz',
        currentWith: 'Client Here',
        noOfJobs: 'Client Here',
        action: '',
    },
    {
        ticketId: 'Ticket Id here',
        client: 'Client Here',
        subject: 'subject Here',
        category: 'category Here',
        serverity: 'serverity Here',
        currentStatus: 'Re-assigned',
        loggedOn: 'Occured',
        logggedBy: 'Jenny Penz',
        currentWith: 'Client Here',
        noOfJobs: 'Client Here',
        action: '',
    },
    {
        ticketId: 'Ticket Id here',
        client: 'Client Here',
        subject: 'subject Here',
        category: 'category Here',
        serverity: 'serverity Here',
        currentStatus: 'Resolved',
        loggedOn: 'Occured',
        logggedBy: 'Jenny Penz',
        currentWith: 'Client Here',
        noOfJobs: 'Client Here',
        action: '',
    },
    {
        ticketId: 'Ticket Id here',
        client: 'Client Here',
        subject: 'subject Here',
        category: 'category Here',
        serverity: 'serverity Here',
        currentStatus: 'Esclated',
        loggedOn: 'Occured',
        logggedBy: 'Jenny Penz',
        currentWith: 'Client Here',
        noOfJobs: 'Client Here',
        action: '',
    },
    {
        ticketId: 'Ticket Id here',
        client: 'Client Here',
        subject: 'subject Here',
        category: 'category Here',
        serverity: 'serverity Here',
        currentStatus: 'Retraced',
        loggedOn: 'Occured',
        logggedBy: 'Jenny Penz',
        currentWith: 'Client Here',
        noOfJobs: 'Client Here',
        action: '',
    },
    {
        ticketId: 'Ticket Id here',
        client: 'Client Here',
        subject: 'subject Here',
        category: 'category Here',
        serverity: 'serverity Here',
        currentStatus: 'Rejected',
        loggedOn: 'Occured',
        logggedBy: 'Jenny Penz',
        currentWith: 'Client Here',
        noOfJobs: 'Client Here',
        action: '',
    },
    {
        ticketId: 'Ticket Id here',
        client: 'Client Here',
        subject: 'subject Here',
        category: 'category Here',
        serverity: 'serverity Here',
        currentStatus: 'Closed',
        loggedOn: 'Occured',
        logggedBy: 'Jenny Penz',
        currentWith: 'Client Here',
        noOfJobs: 'Client Here',
        action: '',
    },
    {
        ticketId: 'Ticket Id here',
        client: 'Client Here',
        subject: 'subject Here',
        category: 'category Here',
        serverity: 'serverity Here',
        currentStatus: 'Reopend',
        loggedOn: 'Occured',
        logggedBy: 'Jenny Penz',
        currentWith: 'Client Here',
        noOfJobs: 'Client Here',
        action: '',
    }
]